version: "3"
services:
  app:
    build:
      args:
        user: socket
        uid: 1001
      context: ./backend
      dockerfile: Dockerfile
    image: incidencias-back:2.0
    restart: always
    container_name: sica4_socket-2
    tty: true
    expose:
      - 7000
    ports:
      - 6002:7000
    volumes:
      - ./code:/app
      - /etc/localtime:/etc/localtime:ro
      - ./cert:/cert
